name: CD
on:
  schedule:
  - cron: 0 0 * * 0

jobs:
  follow:
    name: Follow dprint-plugin-typescript Updates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with: { node-version: 14.x }
    - name: Install Packages
      run: npm install
    - name: Update dprint-plugin-typescript if needed
      id: updateStep
      run: npx ts-node scripts/update-if-needed
    - name: Test
      run: |
        npm run -s test:ci
        npm run -s lint -- --fix
      if: ${{ success() && steps.updateStep.outputs.updated == "yes" }}
    - name: Version Bump
      run: |
        git config user.name mysticatea
        git config user.email public@mysticatea.dev
        git add .
        git commit -m "ðŸš€ update dprint-plugin-typescript"
        npm version ${{ steps.updateStep.outputs.kind }}
      if: ${{ success() && steps.updateStep.outputs.updated == "yes" }}
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: ${{ success() && steps.updateStep.outputs.updated == "yes" }}
